name: ProgressBar
version: "0.2"
license: "GPL-2.0-or-later"
date: 2023-02-22
description: |
    The GAP package ProgressBar displays the progression of an iteration in the terminal.

authors:
    - name: Friedrich Rober
      url: mailto:friedrich.rober@rwth-aachen.de

maintainers:
    - name: Friedrich Rober
      url: mailto:friedrich.rober@rwth-aachen.de

GAP: ">= 4.11"

www: https://lbfm-rwth.github.io/ProgressBar/
readme: README.md
packageinfo: https://lbfm-rwth.github.io/ProgressBar/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/lbfm-rwth/ProgressBar/releases/download/v0.2/ProgressBar-0.2.tar.gz

abstract: |

status: dev
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Rob23</span>]   <b class='BibAuthor'>Rober, F.</b>,
     <i class='BibTitle'>ProgressBar, The GAP package ProgressBar displays the progression of an iteration in the terminal.,
             Version 0.2</i>
     (<span class='BibYear'>2023</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://lbfm-rwth.github.io/ProgressBar/">https://lbfm-rwth.github.io/ProgressBar/</a></span>.
    </p>
    

bibtex: |
    @misc{ ProgressBar0.2,
      author =           {Rober, F.},
      title =            {{ProgressBar},  The  GAP  package ProgressBar displays
                          the  progression  of  an  iteration  in the terminal.,
                          {V}ersion 0.2},
      month =            {Feb},
      year =             {2023},
      note =             {GAP package},
      howpublished =     {\href       {https://lbfm-rwth.github.io/ProgressBar/}
                          {\texttt{https://lbfm-rwth.github.io/}\discretionary
                          {}{}{}\texttt{ProgressBar/}}},
      printedkey =       {Rob23}
    }

